# Generated by Django 3.2.7 on 2021-09-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_company_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='score',
            field=models.FloatField(),
        ),
    ]
