# Generated by Django 3.2.7 on 2021-09-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_company_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='company',
            name='diversity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='glassdoor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='reclameaqui',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
